### ISSUE TITLE
"Promise issues in older browsers" test does not work

### ISSUE THREAD

**Issue by mmermerkaya** [jakearchibald/idb#83]
The promise issue test linked [here](https://github.com/jakearchibald/idb#promise-issues-in-older-browsers) doesn't work. Looks like the CDN that [hosted idb](https://cdn.rawgit.com/jakearchibald/idb/master/lib/idb.js) is [dead](https://rawgit.com/).

**Comment by rkaw92** [comment]
Hi, I've just downloaded a copy of both the HTML file and the JS library (from `/build`), fixed the script path, and attempted to run the test. It appears that, even after working around the CDN issue, the code is incorrect (does not work in the current version of `idb`):
```
TypeError: idb.open is not a function
```

After changing to `idb.openDb`, the test passes.

**Comment by jakearchibald** [comment]
Thanks. I'm currently working on the 4.0.0 branch, which includes much better tests,

**Comment by jakearchibald** [comment]
Shipped!
