### ISSUE TITLE
Issue with 4.0.5

### ISSUE THREAD

**Issue by DaveLomber** [jakearchibald/idb#130]
After upgraded from 4.0.4 to 4.0.5 I started getting the following error:

```
ERROR in ../node_modules/idb/lib/async-iterators.ts:40:5 - error TS2322: Type 'IDBPCursorWithValue<unknown, string[], string, unknown> | IDBPCursorWithValue<unknown, string[], string, string>' is not assignable to type 'IDBPCursor<unknown, string[], string, unknown> | IDBPIndex<unknown, string[], string, string> | IDBPObjectStore<unknown, string[], string>'.
  Type 'IDBPCursorWithValue<unknown, string[], string, string>' is not assignable to type 'IDBPCursor<unknown, string[], string, unknown> | IDBPIndex<unknown, string[], string, string> | IDBPObjectStore<unknown, string[], string>'.
    Type 'IDBPCursorWithValue<unknown, string[], string, string>' is not assignable to type 'IDBPCursor<unknown, string[], string, unknown>'.
      Types of property 'source' are incompatible.
        Type 'IDBPIndex<unknown, string[], string, string>' is missing the following properties from type 'IDBPObjectStore<unknown, string[], string>': indexNames, transaction, add, clear, and 6 more.

40     cursor = await (cursor as IDBPObjectStore | IDBPIndex).openCursor(...args);
```

**Comment by jakearchibald** [comment]
Thanks for the report, I'll take a look

**Comment by jakearchibald** [comment]
@DaveLomber @Txuso can you give me some example code that triggers the above error?

**Comment by smout74** [comment]
I can confirm this error with Ionic 4 + Angular

**Comment by jakearchibald** [comment]
I'm interested in fixing this, but can't without a reproducible test case. Please reopen this when you have one.

I'm unfamiliar with Ionic & Angular, so ideally can you give me a reduced project that only contains what's needed to recreate the issue.
